<script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script><script defer src="https://cdn.jsdelivr.net/gh/vallafederico/hacking-webflow@master/dist/text-split.03.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js"></script><script src="https://unpkg.com/mouse-follower@1/dist/mouse-follower.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/ScrollTrigger.min.js"></script><script src="https://cdn.jsdelivr.net/gh/studio-freight/lenis@0.2.28/bundled/lenis.js"></script><script src="https://player.vimeo.com/api/player.js"></script><script>document.addEventListener('DOMContentLoaded',function(){let videoSlider,gallerySlider;let currentPlayer=null;let isAudioPlaying=!1;let vimeoPlayers={};function initVideoSwiper(){const videoSliderElement=document.querySelector(".swiper.is-video-slider");if(videoSliderElement&&!videoSlider){videoSlider=new Swiper(videoSliderElement,{slidesPerView:'1',speed:1000,grabCursor:!0,mousewheel:{forceToAxis:!0,invert:!1,sensitivity:0.5,thresholdDelta:0,},parallax:!0,loop:!0,direction:'horizontal',keyboard:{enabled:!0,onlyInViewport:!1,},on:{init:function(){initializeAllSlides(this.slides);playVideoInActiveSlideAutoplay(this.activeIndex)},slideChange:function(){handleSlideChange(this)}}});videoSlider.on('slideChangeTransitionEnd',function(){if(videoSlider.realIndex===0){muteAudio()}});setupCustomControls();console.log('Video Swiper initialized')}}
function initGallerySwiper(){const gallerySliderElement=document.querySelector(".swiper.is-gallery");if(gallerySliderElement&&!gallerySlider){gallerySlider=new Swiper(gallerySliderElement,{slidesPerView:1,slidesPerGroup:1,spaceBetween:25,centeredSlides:!0,speed:1000,grabCursor:!0,mousewheel:{forceToAxis:!0,invert:!1,sensitivity:0.5,thresholdDelta:0,},parallax:!0,loop:!0,direction:'horizontal',keyboard:{enabled:!0,onlyInViewport:!1,},});console.log('Gallery Swiper initialized')}}
function initializeAllSlides(slides){slides.forEach((slide,index)=>{const iframe=slide.querySelector('.video-asset');if(iframe&&!vimeoPlayers[index]){const player=new Vimeo.Player(iframe);vimeoPlayers[index]=player;player.setVolume(0);slide.addEventListener('mouseenter',function(){forceAutoplayVideo(index)});slide.addEventListener('touchstart',function(){forceAutoplayVideo(index)})}})}
function forceAutoplayVideo(index){if(vimeoPlayers[index]){vimeoPlayers[index].play().then(()=>{console.log('Video autoplayed by force due to cursor hover')}).catch(error=>{console.log('Autoplay force failed:',error)})}}
function pauseAllVideosExcept(activeIndex){Object.keys(vimeoPlayers).forEach(index=>{if(parseInt(index)!==activeIndex){vimeoPlayers[index].pause().then(()=>{vimeoPlayers[index].setVolume(0)})}});isAudioPlaying=!1}
function handleSlideChange(swiper){pauseAllVideosExcept(swiper.realIndex);playVideoInActiveSlideAutoplay(swiper.realIndex);const activeSlide=swiper.slides[swiper.activeIndex];function handleMouseEnter(){forceAutoplayVideo(swiper.realIndex)}
function handleTouchStart(){forceAutoplayVideo(swiper.realIndex)}
activeSlide.removeEventListener('mouseenter',handleMouseEnter);activeSlide.removeEventListener('touchstart',handleTouchStart);activeSlide.addEventListener('mouseenter',handleMouseEnter);activeSlide.addEventListener('touchstart',handleTouchStart);updateButtonStates()}
function playVideoInActiveSlideAutoplay(index){if(vimeoPlayers[index]){vimeoPlayers[index].setCurrentTime(0).then(()=>{vimeoPlayers[index].setVolume(0);vimeoPlayers[index].play().then(()=>{console.log('Video autoplay di mute')}).catch(error=>{console.log('Autoplay gagal:',error)})});currentPlayer=vimeoPlayers[index]}}
function enableSoundOnActiveSlide(){if(currentPlayer){currentPlayer.setVolume(1).then(()=>{return currentPlayer.play()}).then(()=>{console.log('Sound enabled and video playing on active slide')}).catch((error)=>{console.error('Error enabling sound or playing video:',error)});isAudioPlaying=!0;updateButtonStates()}}
function setupCustomControls(){document.body.addEventListener('click',function(event){const target=event.target.closest('[vimeo]');if(!target)return;const action=target.getAttribute('vimeo');if(action==='play'){enableSoundOnActiveSlide()}else if(action==='pause'){muteAudio()}})}
function muteAudio(){if(currentPlayer){currentPlayer.setVolume(0);isAudioPlaying=!1;updateButtonStates()}}
function updateButtonStates(){const playButtons=document.querySelectorAll('[vimeo="play"]');const pauseButtons=document.querySelectorAll('[vimeo="pause"]');playButtons.forEach(playButton=>{playButton.removeEventListener('click',handlePlayButtonClick);playButton.addEventListener('click',handlePlayButtonClick)});pauseButtons.forEach(pauseButton=>{pauseButton.removeEventListener('click',handlePauseButtonClick);pauseButton.addEventListener('click',handlePauseButtonClick)});if(isAudioPlaying){playButtons.forEach(button=>button.style.display='none');pauseButtons.forEach(button=>button.style.display='flex')}else{playButtons.forEach(button=>button.style.display='flex');pauseButtons.forEach(button=>button.style.display='none')}}
function handlePlayButtonClick(){enableSoundOnActiveSlide()}
function handlePauseButtonClick(){muteAudio()}
const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){if(entry.target.classList.contains('is-video-slider')){initVideoSwiper()}else if(entry.target.classList.contains('is-gallery')){initGallerySwiper()}
observer.unobserve(entry.target)}})},{threshold:0});const swiperContainers=document.querySelectorAll('.swiper.is-video-slider, .swiper.is-gallery');swiperContainers.forEach(container=>observer.observe(container))});</script><script>let firstClientLogo;function displayFirstClientLogo(){const firstClientTitle=document.querySelector('.client-name');if(firstClientTitle){const clientId=firstClientTitle.dataset.clientId;firstClientLogo=document.querySelector(`.client-logo[data-client-id="${clientId}"]`);if(firstClientLogo){firstClientLogo.style.display='block'}}}
function showLogo(event){const clientId=event.target.dataset.clientId;const logo=document.querySelector(`.client-logo[data-client-id="${clientId}"]`);if(logo){if(firstClientLogo&&firstClientLogo!==logo){firstClientLogo.style.display='none'}
logo.style.display='block'}}
function hideLogo(event){const clientId=event.target.dataset.clientId;const logo=document.querySelector(`.client-logo[data-client-id="${clientId}"]`);if(logo){if(logo!==firstClientLogo){logo.style.display='none';if(firstClientLogo){firstClientLogo.style.display='block'}}}}
const clientTitles=document.querySelectorAll('.client-name');clientTitles.forEach(title=>{title.addEventListener('mouseenter',showLogo);title.addEventListener('mouseleave',hideLogo)});window.addEventListener('load',displayFirstClientLogo);</script><script>document.addEventListener('DOMContentLoaded',function(){const ele=document.getElementById('clickanddrag');if(window.innerWidth>768){ele.style.cursor='grab';let pos={top:0,left:0,x:0,y:0};const mouseDownHandler=function(e){ele.style.cursor='grabbing';ele.style.userSelect='none';pos={left:ele.scrollLeft,top:ele.scrollTop,x:e.clientX,y:e.clientY,};document.addEventListener('mousemove',mouseMoveHandler);document.addEventListener('mouseup',mouseUpHandler)};const mouseMoveHandler=function(e){const dx=e.clientX-pos.x;const dy=e.clientY-pos.y;ele.scrollTop=pos.top-dy;ele.scrollLeft=pos.left-dx};const mouseUpHandler=function(){ele.style.cursor='grab';ele.style.removeProperty('user-select');document.removeEventListener('mousemove',mouseMoveHandler);document.removeEventListener('mouseup',mouseUpHandler)};ele.addEventListener('mousedown',mouseDownHandler)}});</script><script>document.addEventListener('DOMContentLoaded',function(){const headerDesktop=document.querySelector('.header');const headerMobile=document.querySelector('.header-mobile');let lastScrollTop=0;let scrollThreshold=100;let delta=50;function handleScroll(header){let scrollTop=window.pageYOffset||document.documentElement.scrollTop;if(Math.abs(lastScrollTop-scrollTop)<=delta){return}
if(scrollTop>lastScrollTop&&scrollTop>scrollThreshold){header.classList.remove('header-visible');header.classList.add('header-hidden')}else{header.classList.remove('header-hidden');header.classList.add('header-visible')}
if(scrollTop>scrollThreshold){header.classList.remove('header-light');header.classList.add('header-dark')}else{header.classList.remove('header-dark');header.classList.add('header-light')}
lastScrollTop=scrollTop}
window.addEventListener('scroll',function(){if(window.innerWidth>768){handleScroll(headerDesktop)}else{handleScroll(headerMobile)}});window.addEventListener('resize',function(){if(window.innerWidth>768){headerMobile.classList.remove('header-hidden','header-visible','header-dark','header-light')}else{headerDesktop.classList.remove('header-hidden','header-visible','header-dark','header-light')}})});</script><script>const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting&&entry.target.classList.contains('hero_vid')){lazyLoadVimeoVideo(entry.target);observer.unobserve(entry.target)}})},{threshold:0});function initLazyLoad(){const heroVideos=document.querySelectorAll('.hero_vid');heroVideos.forEach(video=>observer.observe(video))}</script><script>const lenis=new Lenis({duration:1.2,easing:(t)=>Math.min(1,1.001-Math.pow(2,-10*t)),direction:'vertical',gestureDirection:'vertical',smooth:!0,mouseMultiplier:1,smoothTouch:!1,touchMultiplier:2,infinite:!1,})
lenis.on('scroll',({scroll,limit,velocity,direction,progress})=>{console.log({scroll,limit,velocity,direction,progress})})
function raf(time){lenis.raf(time)
requestAnimationFrame(raf)}
requestAnimationFrame(raf)</script><script>var currentArticle=document.querySelector('.current-article-number').innerHTML;var otherArticle=document.querySelectorAll('.article-number');for(var i=0;i<otherArticle.length;i++){if(otherArticle[i].innerHTML==currentArticle){try{var targetButton=otherArticle[i+1].parentNode.querySelector('.next-button');targetButton.style.display='block'}catch{console.log('No more articles')}
try{var targetButton=otherArticle[i-1].parentNode.querySelector('.previous-button');targetButton.style.display='block'}catch{console.log('No previous articles')}}}</script>